$ErrorActionPreference = "Stop"

$RepoRoot = $PSScriptRoot
$SourceVimrc = Join-Path $RepoRoot "vim\vimrc"
$TargetVimrc = Join-Path $HOME "_vimrc"

if (-not (Test-Path $SourceVimrc)) {
    throw "Vim config not found: $SourceVimrc"
}

# Back up an existing _vimrc unless it was created by this installer.
if (Test-Path $TargetVimrc) {
    $existing = Get-Content -Path $TargetVimrc -Raw -ErrorAction SilentlyContinue

    if ($existing -notmatch "Managed by dotfiles/install.ps1") {
        $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
        $backup = "$TargetVimrc.backup-$timestamp"
        Copy-Item -Path $TargetVimrc -Destination $backup
        Write-Host "Existing _vimrc backed up to: $backup"
    }
}

# Vim single-quoted strings escape a quote by doubling it.
$escapedSource = $SourceVimrc.Replace("'", "''")

$loader = @"
" Managed by dotfiles/install.ps1
" Do not edit this file directly.
" Edit: $SourceVimrc

execute 'source ' . fnameescape('$escapedSource')
"@

# Write UTF-8 without BOM for compatibility with both Windows PowerShell and PowerShell 7.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($TargetVimrc, $loader, $utf8NoBom)

Write-Host ""
Write-Host "Vim dotfiles installed."
Write-Host "Loader : $TargetVimrc"
Write-Host "Config : $SourceVimrc"
Write-Host ""
Write-Host "Open Vim and run ':scriptnames' to confirm that vim\vimrc is loaded."
